# Generated by Django 3.1.1 on 2020-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAU', models.IntegerField()),
                ('MAU', models.IntegerField()),
                ('date_day', models.CharField(max_length=40)),
                ('date_month', models.CharField(max_length=50)),
                ('MAUgrowth', models.IntegerField()),
                ('DAUgrowth', models.IntegerField()),
                ('trMAU', models.CharField(max_length=10)),
                ('trDAU', models.CharField(max_length=10)),
                ('colD', models.CharField(max_length=10)),
                ('colM', models.CharField(max_length=10)),
            ],
        ),
    ]
