# Generated by Django 3.1.2 on 2020-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showusers', '0004_auto_20200929_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayval',
            name='DAUgrowth',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='MAUgrowth',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='colD',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='colM',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='date_day',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='date_month',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='triaDAU',
        ),
        migrations.RemoveField(
            model_name='dayval',
            name='triaMAU',
        ),
        migrations.AddField(
            model_name='dayval',
            name='prevDAU',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayval',
            name='prevMAU',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
