# Generated by Django 3.1.2 on 2020-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showusers', '0005_auto_20201026_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayval',
            name='DAU',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dayval',
            name='MAU',
            field=models.IntegerField(max_length=10),
        ),
    ]
