# Generated by Django 3.1.2 on 2020-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showusers', '0006_auto_20201026_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayval',
            name='DAU',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayval',
            name='MAU',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayval',
            name='prevDAU',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayval',
            name='prevMAU',
            field=models.IntegerField(),
        ),
    ]
