# Generated by Django 3.1.2 on 2020-10-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showusers', '0007_auto_20201026_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayVal',
            new_name='FastProd_DATA',
        ),
    ]
