# Generated by Django 3.1.2 on 2020-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showusers', '0008_auto_20201026_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApp_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=40)),
                ('DAU', models.IntegerField()),
                ('MAU', models.IntegerField()),
                ('prevDAU', models.IntegerField()),
                ('prevMAU', models.IntegerField()),
            ],
        ),
    ]
